# Generated by Django 3.1.5 on 2021-02-22 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='view',
            field=models.IntegerField(default=0),
        ),
    ]
