# Generated by Django 3.1.5 on 2021-03-04 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_todo_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
    ]
