# Generated by Django 3.1.4 on 2021-03-28 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0004_auto_20210305_0533'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-create_date']},
        ),
    ]
