# Generated by Django 3.1.4 on 2021-03-31 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0006_todo_imgae'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='imgae',
            new_name='image',
        ),
    ]
